site_name: PnP XAI Docs
site_url: https://openxaiproject.github.io/pnpxai/
theme: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
          selection:
            inherited_members: true
          rendering:
                  show_root_heading: true  # actually display anything at all...
                  show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
                  show_if_no_docstring: true
                  show_signature_annotations: true
                  show_source: false  # don't include source code
                  members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                  heading_level: 4
nav:
  - Home: index.md
  - API:
    - Project: api/project.md
    - Experiment: api/experiment.md
    - 'Auto Experiment': api/auto_experiment.md