site_name: PnP XAI Docs
site_url: https://openxaiproject.github.io/pnpxai/
theme: 
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico

plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            inherited_members: true
          rendering:
                  show_root_heading: true  # actually display anything at all...
                  show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
                  show_if_no_docstring: true
                  show_signature_annotations: true
                  show_source: false  # don't include source code
                  members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                  heading_level: 4

nav:
  - Home: index.md
  - API:
    - Core:
      - Experiment: api/core/experiment.md
      - 'Auto Explanation': api/core/auto_explanation.md
      - Modality: api/core/modality.md
      - Recommender: api/core/recommender.md
      - Detector: api/core/detector.md
    - Evaluator:
      - Metrics: api/evaluator/metrics.md
      - Optimizer: api/evaluator/optimizer.md
    - Explainer:
      - Base: api/explainer/base.md
      - GradCam: api/explainer/grad_cam.md
      - GuidedGradCam: api/explainer/guided_grad_cam.md
      - Gradient: api/explainer/gradient.md
      - GradientXInput: api/explainer/grad_x_input.md
      - SmoothGrad: api/explainer/smooth_grad.md
      - VarGrad: api/explainer/var_grad.md
      - IntegratedGradients: api/explainer/ig.md
      - LRP: api/explainer/lrp.md
      - RAP: api/explainer/rap.md
      - KernelShap: api/explainer/kernel_shap.md
      - Lime: api/explainer/lime.md
      - AttentionRollout: api/explainer/attn_rollout.md
  - Detector: detector.md
  - Explainer: explainer.md
  - Recommender: recommender.md
  - Evaluator: evaluator.md
  - Optimizer: optimizer.md

watch:
  - pnpxai