site_name: PnP XAI Docs
site_url: https://openxaiproject.github.io/pnpxai/
theme: material
plugins:
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
          selection:
            inherited_members: true
nav:
  - Home: index.md
  - Reference:
    - API: api/index.md
    - Project: api/project.md
    - Experiment: api/experiment.md
    - 'Auto Experiment': api/auto_experiment.md