
# This file is automatically generated during the generation of setup.py
# Copyright 2023-2026, Open XAI PnP
author = "Team SAIL"
author_email = "open.xai@gmail.com"
version = "0.0.1"
full_version = "0.0.1"
git_version = '3c7df19e73000004f1687e9a9a4f3d7ba28b93a5'
release = False
homepage = "https://github.com/jasmcaus/caer"
