
# This file is automatically generated during the generation of setup.py
# Copyright 2023-2026, Open XAI PnP
author = "Team SAIL"
author_email = "open.xai@gmail.com"
version = "0.0.1"
full_version = "0.0.1"
git_version = '38689708876a9f8496dae8e1651fa645d2989abb'
release = False
homepage = "https://github.com/jasmcaus/caer"
