
# This file is automatically generated during the generation of setup.py
# Copyright 2023-2026, PnP XAI
author = "Team SAIL"
author_email = "open.xai@gmail.com"
version = "0.0.1"
full_version = "0.0.1"
<<<<<<< HEAD:open_xai/_meta.py
git_version = '38689708876a9f8496dae8e1651fa645d2989abb'
=======
git_version = 'b9c7bbd715e0dd09eb6f401336bac9a23857dfbf'
>>>>>>> 4a7e64645f9ad5ff1ea5be3d7d089f31e4683e28:pnpxai/_meta.py
release = False
homepage = "https://github.com/jasmcaus/caer"
