
# This file is automatically generated during the generation of setup.py
# Copyright 2023-2026, Open XAI PnP
author = "Team SAIL"
author_email = "open.xai@gmail.com"
version = "0.0.1"
full_version = "0.0.1"
git_version = '8d4cb8c3fd976c60d6f23941938a46579b36516a'
release = False
homepage = "https://github.com/OpenXAIProject/pnpxai"
