
# This file is automatically generated during the generation of setup.py
# Copyright 2023-2026, XAI PnP
author = "Team SAIL"
author_email = "open.xai@gmail.com"
version = "0.0.1"
full_version = "0.0.1"
git_version = '52ea6246c77108e817d1f8742124aae39276b3d9'
release = False
homepage = "https://github.com/jasmcaus/caer"
