
# This file is automatically generated during the generation of setup.py
# Copyright 2023-2026, XAI PnP
author = "Team SAIL"
author_email = "open.xai@gmail.com"
version = "0.0.1"
full_version = "0.0.1"
git_version = 'a812ab243e29b82c4030fdc47db3086dd0d4f939'
release = False
homepage = "https://github.com/jasmcaus/caer"
