
# This file is automatically generated during the generation of setup.py
# Copyright 2023-2026, XAI PnP
author = "Team SAIL"
author_email = "open.xai@gmail.com"
version = "0.0.1"
full_version = "0.0.1"
git_version = '6027f1c158f118f0fb42d19b607184893307acbc'
release = False
homepage = "https://github.com/jasmcaus/caer"
